# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Notes
tagline:          'just to not forget'
description:      'Notes mainly on linux on x86, Raspberry Pi, and some useful tricks.'
url:              http://prosciutboy.github.io

author:
  name:           'prosciutboy'
  url:            https://twitter.com/prosciutboy

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/prosciutboy
